Add frontend example for Installation type (B) - package
Laravel-Backpack/MenuCRUD pull request #59
Opened 2020-12-19 14:34 UTC by mansourcodes

added frontend example for Installation type (B) - package

2020-12-19 17:37 UTC, promatik requested changes
Hi @mansourcodes, good catch, it's better to advise people about this.
I think there is no need to add a new example code block on this, the note is enough, what do you think?

2020-12-19 17:37 UTC, promatik commented on README.md
> +```
```suggestion
For Installation type (B), change the namespace to `Backpack\MenuCRUD\app\Models`.
```

2020-12-19 19:38 UTC, mansourcodes commented
Agree 👍

2020-12-19 22:47 UTC, promatik approved these changes

2020-12-20 12:39 UTC, mansourcodes reviewed
Great, it's more clear for users to read

2020-12-22 13:54 UTC, merged